
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"

  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vbguest.auto_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.hostname = "db01"
  config.vm.network "private_network", ip: "192.168.1.4"  
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.provision "shell", path: "provision.sh" 
end
